//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the rgbd_utils package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __rgbd_utils__PATH_PARAMSCONFIG_H__
#define __rgbd_utils__PATH_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace rgbd_utils
{
  class path_paramsConfigStatics;
  
  class path_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(path_paramsConfig &config, const path_paramsConfig &max, const path_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const path_paramsConfig &config1, const path_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, path_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const path_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, path_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const path_paramsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T path_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (path_paramsConfig::* field);

      virtual void clamp(path_paramsConfig &config, const path_paramsConfig &max, const path_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const path_paramsConfig &config1, const path_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, path_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const path_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, path_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const path_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 11 "cfg/params.cfg"
      double ant_steepness;
//#line 12 "cfg/params.cfg"
      double ant_uphill_factor;
//#line 13 "cfg/params.cfg"
      double ant_heightcost_factor;
//#line 14 "cfg/params.cfg"
      double ant_hillside_factor;
//#line 16 "cfg/params.cfg"
      double ant_enemy_factor;
//#line 17 "cfg/params.cfg"
      bool ant_use_smoothing;
//#line 18 "cfg/params.cfg"
      bool ant_use_four;
//#line 20 "cfg/params.cfg"
      double scale;
//#line 22 "cfg/params.cfg"
      double dist_treshold;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("path_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const path_paramsConfig &__max__ = __getMax__();
      const path_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const path_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const path_paramsConfig &__getDefault__();
    static const path_paramsConfig &__getMax__();
    static const path_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const path_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void path_paramsConfig::ParamDescription<std::string>::clamp(path_paramsConfig &config, const path_paramsConfig &max, const path_paramsConfig &min) const
  {
    return;
  }

  class path_paramsConfigStatics
  {
    friend class path_paramsConfig;
    
    path_paramsConfigStatics()
    {
//#line 11 "cfg/params.cfg"
      __min__.ant_steepness = 0.0;
//#line 11 "cfg/params.cfg"
      __max__.ant_steepness = 90.0;
//#line 11 "cfg/params.cfg"
      __default__.ant_steepness = 45.0;
//#line 11 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("ant_steepness", "double", 0, "max angle (deg)", "", &path_paramsConfig::ant_steepness)));
//#line 12 "cfg/params.cfg"
      __min__.ant_uphill_factor = 1.0;
//#line 12 "cfg/params.cfg"
      __max__.ant_uphill_factor = 5.0;
//#line 12 "cfg/params.cfg"
      __default__.ant_uphill_factor = 3.0;
//#line 12 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("ant_uphill_factor", "double", 0, "ant_uphill_factor", "", &path_paramsConfig::ant_uphill_factor)));
//#line 13 "cfg/params.cfg"
      __min__.ant_heightcost_factor = 0.0;
//#line 13 "cfg/params.cfg"
      __max__.ant_heightcost_factor = 0.5;
//#line 13 "cfg/params.cfg"
      __default__.ant_heightcost_factor = 0.1;
//#line 13 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("ant_heightcost_factor", "double", 0, "ant_cost_factor", "", &path_paramsConfig::ant_heightcost_factor)));
//#line 14 "cfg/params.cfg"
      __min__.ant_hillside_factor = 0.0;
//#line 14 "cfg/params.cfg"
      __max__.ant_hillside_factor = 50.0;
//#line 14 "cfg/params.cfg"
      __default__.ant_hillside_factor = 14.0;
//#line 14 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("ant_hillside_factor", "double", 0, "ant_hillside_factor", "", &path_paramsConfig::ant_hillside_factor)));
//#line 16 "cfg/params.cfg"
      __min__.ant_enemy_factor = 0.0;
//#line 16 "cfg/params.cfg"
      __max__.ant_enemy_factor = 50.0;
//#line 16 "cfg/params.cfg"
      __default__.ant_enemy_factor = 14.0;
//#line 16 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("ant_enemy_factor", "double", 0, "enemy", "", &path_paramsConfig::ant_enemy_factor)));
//#line 17 "cfg/params.cfg"
      __min__.ant_use_smoothing = 0;
//#line 17 "cfg/params.cfg"
      __max__.ant_use_smoothing = 1;
//#line 17 "cfg/params.cfg"
      __default__.ant_use_smoothing = 0;
//#line 17 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<bool>("ant_use_smoothing", "bool", 0, "ant_use_smoothing", "", &path_paramsConfig::ant_use_smoothing)));
//#line 18 "cfg/params.cfg"
      __min__.ant_use_four = 0;
//#line 18 "cfg/params.cfg"
      __max__.ant_use_four = 1;
//#line 18 "cfg/params.cfg"
      __default__.ant_use_four = 1;
//#line 18 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<bool>("ant_use_four", "bool", 0, "ant_use_four", "", &path_paramsConfig::ant_use_four)));
//#line 20 "cfg/params.cfg"
      __min__.scale = 0.0;
//#line 20 "cfg/params.cfg"
      __max__.scale = 2.0;
//#line 20 "cfg/params.cfg"
      __default__.scale = 1.0;
//#line 20 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("scale", "double", 0, "scale", "", &path_paramsConfig::scale)));
//#line 22 "cfg/params.cfg"
      __min__.dist_treshold = 0.0;
//#line 22 "cfg/params.cfg"
      __max__.dist_treshold = 1000.0;
//#line 22 "cfg/params.cfg"
      __default__.dist_treshold = 50.0;
//#line 22 "cfg/params.cfg"
      __param_descriptions__.push_back(path_paramsConfig::AbstractParamDescriptionConstPtr(new path_paramsConfig::ParamDescription<double>("dist_treshold", "double", 0, "dist_treshold", "", &path_paramsConfig::dist_treshold)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<path_paramsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<path_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    path_paramsConfig __max__;
    path_paramsConfig __min__;
    path_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const path_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static path_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &path_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const path_paramsConfig &path_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const path_paramsConfig &path_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const path_paramsConfig &path_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<path_paramsConfig::AbstractParamDescriptionConstPtr> &path_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const path_paramsConfigStatics *path_paramsConfig::__get_statics__()
  {
    const static path_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = path_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PATH_PARAMSRECONFIGURATOR_H__
